# Generated by Django 5.0.2 on 2024-03-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
