# Generated by Django 5.0.2 on 2024-03-17 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_soft', '0005_remove_saledetail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_detail', to='admin_soft.sale'),
        ),
    ]
